[package]
name = "game-of-life"
version = "1.7.0"
authors = ["Billie Thompson <billie+game-of-life@billiecodes.com>"]
edition = "2018"
description = "An implementation of the game of life."
license = "Creative Commons Zero v1.0 Universal"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.17"
rand = "0.7"
clap = "~2.33"
