[package]
name = "game-of-life"
version = "0.4.0"
authors = ["Billie Thompson <billie@billiecodes.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.17"
rand = "0.7"
clap = "~2.33"