FROM goreleaser/nfpm@sha256:44ab1c1726fc775a8e7d6fcd216ed7632b52af4b8f43e2c1daec12a735e7851b AS nfpm

FROM --platform=$BUILDPLATFORM tonistiigi/xx@sha256:923441d7c25f1e2eb5789f82d987693c47b8ed987c4ab3b075d6ed2b5d6779a3 AS xx
ARG TARGETPLATFORM

FROM --platform=$BUILDPLATFORM rust:alpine@sha256:661d708cc863ce32007cf46807a72062a80d2944a6fae9e0d83742d2e04d5375 AS builder
RUN apk add clang lld openssl-dev curl bash
# copy xx scripts to your build stage
COPY --from=xx / /
ARG TARGETPLATFORM
ARG VER
ENV VER=$VER

COPY --from=nfpm "/usr/bin/nfpm" "/usr/bin/nfpm"
RUN xx-apk add --no-cache musl-dev zlib-dev zlib-static openssl-dev openssl-libs-static pkgconfig alpine-sdk

WORKDIR /app
RUN cargo new --lib game-of-life
WORKDIR /app/game-of-life
COPY Cargo.* ./
RUN xx-cargo build --release --target-dir ./build
COPY . ./
RUN xx-cargo build --release --target-dir ./build && \
    xx-verify --static "./build/$(xx-cargo --print-target-triple)/release/game-of-life" && \
    cp -v  "./build/$(xx-cargo --print-target-triple)/release/game-of-life" "./game-of-life"

COPY nfpm.yaml nfpm.yaml
RUN mkdir /PACKS && \
    GOARCH="$(xx-info arch)" nfpm pkg --packager archlinux --config="nfpm.yaml" --target="/PACKS" && \
    GOARCH="$(xx-info arch)" nfpm pkg --packager rpm --config="nfpm.yaml" --target="/PACKS" && \
    GOARCH="$(xx-info arch)" nfpm pkg --packager apk --config="nfpm.yaml" --target="/PACKS" && \
    GOARCH="$(xx-info arch)" nfpm pkg --packager deb --config="nfpm.yaml" --target="/PACKS"
FROM scratch
USER nonroot
COPY --from=builder /PACKS .
COPY --from=builder /app/game-of-life/game-of-life .
